# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    env:
      PATH: /home/gitpod/.pyenv/bin:/home/gitpod/.local/bin:/workspace/Apps/jdk-19/bin:/workspace/go/bin:/workspace/miniconda3/bin:/workspace/dotnet:/workspace/bin:/worspace/local/bin:$PATH
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
